In [2]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
import anndata
import scanpy as sc

In [3]:
def preprocess_data(adata: anndata.AnnData, scale :bool=True):
    """Preprocessing dataset: filtering genes/cells, normalization and scaling."""
    sc.pp.filter_cells(adata, min_counts=5000)
    sc.pp.filter_cells(adata, min_genes=500)

    sc.pp.normalize_per_cell(adata, counts_per_cell_after=1e4)
    adata.raw = adata

    sc.pp.log1p(adata)
    if scale:
        sc.pp.scale(adata, max_value=10, zero_center=True)
        adata.X[np.isnan(adata.X)] = 0

    return adata

In [4]:
def pca(X, num_components: int):
    return PCA(num_components).fit_transform(X)

In [5]:
data = anndata.read_csv('scRNAseq_human_pancreas.csv')

/Users/luannguyen/git/scratch_ml/.venv/lib/python3.10/site-packages/anndata/utils.py:434: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)


In [6]:
processed_data = preprocess_data(data)

/var/folders/mq/tbvq251163q8b_jr0pwn74xw0000gn/T/ipykernel_12025/1847071818.py:6: FutureWarning: Use sc.pp.normalize_total instead
  sc.pp.normalize_per_cell(adata, counts_per_cell_after=1e4)
/Users/luannguyen/git/scratch_ml/.venv/lib/python3.10/site-packages/scanpy/preprocessing/_simple.py:590: FutureWarning: Use sc.pp.normalize_total instead
  normalize_per_cell(


In [7]:
X = pca(processed_data.X, 100)

In [8]:
X.shape

(4359, 100)

In [9]:
np.random.choice(a=X.shape[0], size=5, replace=False)

array([2625,  281, 2160,  926,  602])

In [16]:
X1 = X[:, np.newaxis, :]

In [40]:
test1 = np.array([
    [1,2],
    [4,5],
    [7,8]
])

test2 = np.array([
    [11,12],
    [14,15],
    [17,18]
])

test1 = test1[:, np.newaxis, :]
test2_1 = test2[np.newaxis, :, :]
test2_2 = test2[:, :, np.newaxis]
print(test1)
print(test2)
print("\nResult 1:")
print(test2_1 - test1)
print("\nResult 2:")
print(test2_2 - test1)

[[[1 2]]

 [[4 5]]

 [[7 8]]]
[[11 12]
 [14 15]
 [17 18]]

Result 1:
[[[10 10]
  [13 13]
  [16 16]]

 [[ 7  7]
  [10 10]
  [13 13]]

 [[ 4  4]
  [ 7  7]
  [10 10]]]

Result 2:
[[[10  9]
  [11 10]]

 [[10  9]
  [11 10]]

 [[10  9]
  [11 10]]]
